version: "3"

services:
    redis:
        image: redis/redis-stack-server:6.2.6-v7
        container_name: redis

    fastapi:
        image: umbreella/funbox_test:latest
        container_name: fastapi
        ports:
            - 8000:8000
        environment:
            - ENV_FILE=.env
        volumes:
            - .env.fastapi:/usr/src/app/.env
