version: "3"

services:
  redis:
    image: redis/redis-stack-server:6.2.6-v7
    container_name: redis
    ports:
      - 6379:6379

  redis-ui:
    image: redislabs/redisinsight:1.14.0
    container_name: redis-ui
    ports:
      - 8001:8001
